image:
  file: .docker/Dockerfile

vscode:
  extensions:
    - jroesch.lean

tasks:
  - init: |
      leanpkg configure
      leanproject get-cache --fallback=download-all
      leanproject build
    command: . /home/gitpod/.profile
